apiVersion: devops.kubesphere.io/v1alpha3
kind: ClusterStepTemplate
metadata:
  name: git
  labels:
    step.devops.kubesphere.io/category: "SCM"
  annotations:
    devops.kubesphere.io/displayNameZH: "Git Clone"
    devops.kubesphere.io/descriptionZH: "拉取 Git 仓库的代码"
    devops.kubesphere.io/displayNameEN: "Git Clone"
    devops.kubesphere.io/descriptionEN: "Pull code from Git-Repo"
    step.devops.kubesphere.io/icon: "git"
spec:
  runtime: dsl
  parameters:
    - name: url
      type: string
      display: 'Repository URL'
      required: true
    - name: credentialsId
      type: secret
      display: 'Credential Name'
    - name: branch
      type: string
      display: 'Branch'
      defaultValue: 'master'
      required: true
    - name: importCodeRepo
      type: importCodeRepo
      reactions: '[{"target": "url", "fulfill": {"state": {"value": "{{$context?.getRepoUrl?.($self.value)}}"}}}, {"target": "credentialsId", "fulfill": {"state": {"value": "{{$self.value?.secret}}"}}}]'
  template: |
    {
      "arguments": [
        {
          "key": "url",
          "value": {
            "isLiteral": true,
            "value": "{{.param.url}}"
          }
        },
        {
          "key": "credentialsId",
          "value": {
            "isLiteral": true,
            "value": "{{.param.credentialsId.name}}"
          }
        },
        {
          "key": "branch",
          "value": {
            "isLiteral": true,
            "value": "{{.param.branch}}"
          }
        },
        {
          "key": "changelog",
          "value": {
            "isLiteral": true,
            "value": true
          }
        },
        {
          "key": "poll",
          "value": {
            "isLiteral": true,
            "value": false
          }
        }
      ],
      "name": "git"
    }
